name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    name: Build & Push Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag stanthikun802/clcm3504-sorawat-final:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push stanthikun802/clcm3504-sorawat-final:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull stanthikun802/clcm3504-sorawat-final:latest
            docker stop clcm3504-sorawat-final && docker rm clcm3504-sorawat-final
            docker run -d -p 80:80 --name clcm3504-sorawat-final stanthikun802/clcm3504-sorawat-final:latest
            docker image prune -f

